# Generated by Django 2.2.1 on 2020-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
