# Generated by Django 2.2.1 on 2020-06-22 05:45

from django.db import migrations, models
import justchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0002_auto_20200622_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='profile/avatar.png', upload_to=justchat.models.directory_path),
        ),
    ]
