# Generated by Django 2.2.1 on 2020-06-22 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import justchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0003_auto_20200622_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(upload_to=justchat.models.directory_path),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('a_party_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a_party_user', to=settings.AUTH_USER_MODEL)),
                ('b_arty_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b_arty_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
