# Generated by Django 2.2.1 on 2020-06-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justchat', '0004_auto_20200622_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='b_arty_user',
            new_name='b_party_user',
        ),
    ]
